Resources:
  PasswordSecret: # Used in the HealthCheck handler in the application code.
    Type: AWS::SecretsManager::Secret
    Properties:
      Description: 'This is my rds instance secret'
      GenerateSecretString:
        SecretStringTemplate: '{"username": "admin"}'
        GenerateStringKey: 'password'
        PasswordLength: 16
        ExcludeCharacters: '"@/\'

Outputs:
  PasswordSecret:
    Value: !Ref PasswordSecret